version: "3.1"
services:
  mysql:
    image: mysql:9.2
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      LANG: C.UTF_8